spring:
  application:
    name: backend

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      data-source-properties:
        prepareThreshold: 0
        preparedStatementCacheQueries: 0

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true


server:
  port: ${PORT:8080}

supabase:
  url: ${SUPABASE_URL:https://your-project-id.supabase.co}

app:
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000,https://algobuddy.vercel.app,https://algobuddy.me,https://www.algobuddy.me}
