export const ALGORITHM_PSEUDOCODE = {
  "bfs": [
    "BFS(G, startNode):",
    "  let Q be a queue",
    "  mark startNode as visited",
    "  Q.enqueue(startNode)",
    "  while Q is not empty:",
    "    u = Q.dequeue()",
    "    for each neighbor v of u:",
    "      if v is not visited:",
    "        mark v as visited",
    "        Q.enqueue(v)"
  ],
  "dfs": [
    "DFS(G, u):",
    "  mark u as visited",
    "  push u to stack",
    "  for each neighbor v of u:",
    "    if v is not visited:",
    "      DFS(G, v)",
    "  pop u from stack"
  ],
  "dijkstra": [
    "Dijkstra(G, startNode):",
    "  for each node v in G:",
    "    dist[v] = ∞",
    "  dist[startNode] = 0",
    "  let PQ be a priority queue of nodes",
    "  while PQ is not empty:",
    "    u = PQ.extractMin()",
    "    for each neighbor v of u:",
    "      newDist = dist[u] + weight(u, v)",
    "      if newDist < dist[v]:",
    "        dist[v] = newDist",
    "        PQ.decreaseKey(v, newDist)"
  ],
  "a-star": [
    "AStar(G, startNode, goalNode):",
    "  for each node v in G:",
    "    gScore[v] = ∞, fScore[v] = ∞",
    "  gScore[startNode] = 0",
    "  fScore[startNode] = h(startNode, goalNode)",
    "  let openSet be a priority queue of nodes",
    "  while openSet is not empty:",
    "    u = openSet.extractMin(fScore)",
    "    if u == goalNode: return path",
    "    for each neighbor v of u:",
    "      newGScore = gScore[u] + weight(u, v)",
    "      if newGScore < gScore[v]:",
    "        gScore[v] = newGScore",
    "        fScore[v] = gScore[v] + h(v, goalNode)",
    "        openSet.add(v)"
  ],
  "bellman-ford": [
    "BellmanFord(G, startNode):",
    "  for each node v in G:",
    "    dist[v] = ∞",
    "  dist[startNode] = 0",
    "  for i from 1 to |V|-1:",
    "    for each edge (u, v) in G:",
    "      if dist[u] + weight(u,v) < dist[v]:",
    "        dist[v] = dist[u] + weight(u,v)",
    "  for each edge (u, v) in G:",
    "    if dist[u] + weight(u,v) < dist[v]:",
    "      return 'Negative Cycle Detected'"
  ],
  "floyd-warshall": [
    "FloydWarshall(G):",
    "  let dist be a |V| x |V| array",
    "  for each node u, v in G:",
    "    dist[u][v] = weight(u, v) or ∞",
    "  for each node k in G:",
    "    for each node i in G:",
    "      for each node j in G:",
    "        if dist[i][j] > dist[i][k] + dist[k][j]:",
    "          dist[i][j] = dist[i][k] + dist[k][j]"
  ],
  "prim": [
    "Prim(G, startNode):",
    "  for each node v in G:",
    "    key[v] = ∞, inMST[v] = false",
    "  key[startNode] = 0",
    "  while there are nodes not in MST:",
    "    u = node not in MST with min key",
    "    inMST[u] = true",
    "    for each neighbor v of u:",
    "      if inMST[v] == false and weight(u, v) < key[v]:",
    "        key[v] = weight(u, v)"
  ],
  "kruskal": [
    "Kruskal(G):",
    "  let MST be empty",
    "  for each node v in G:",
    "    MakeSet(v)",
    "  sort edges of G in ascending weight order",
    "  for each edge (u, v) in sorted edges:",
    "    if Find(u) != Find(v):",
    "      add (u, v) to MST",
    "      Union(u, v)"
  ],
  "topological-sort": [
    "TopologicalSort(G):",
    "  let inDegree map store incoming edges count",
    "  let Q be a queue of nodes with inDegree == 0",
    "  let order be an empty list",
    "  while Q is not empty:",
    "    u = Q.dequeue()",
    "    add u to order",
    "    for each neighbor v of u:",
    "      inDegree[v] -= 1",
    "      if inDegree[v] == 0:",
    "        Q.enqueue(v)"
  ],
  "kosaraju": [
    "Kosaraju(G):",
    "  let stack be empty",
    "  for each node v in G:",
    "    if v is unvisited: DFS(G, v, stack)",
    "  reverse all edges in G to create G^T",
    "  mark all nodes as unvisited",
    "  while stack is not empty:",
    "    u = stack.pop()",
    "    if u is unvisited:",
    "      DFS(G^T, u, SCC)"
  ],
  "tarjan": [
    "Tarjan(G):",
    "  let index = 0, stack = empty",
    "  for each node v in G:",
    "    if v.index is undefined:",
    "      StrongConnect(v)",
    "",
    "StrongConnect(v):",
    "  v.index = v.lowlink = index++",
    "  stack.push(v); v.onStack = true",
    "  for each neighbor w of v:",
    "    if w.index is undefined:",
    "      StrongConnect(w)",
    "      v.lowlink = min(v.lowlink, w.lowlink)",
    "    else if w.onStack:",
    "      v.lowlink = min(v.lowlink, w.index)",
    "  if v.lowlink == v.index:",
    "    pop nodes from stack until v is popped"
  ],
  "ford-fulkerson": [
    "FordFulkerson(G, s, t):",
    "  Initialize max_flow = 0",
    "  while there exists an augmenting path p from s to t:",
    "    find bottleneck capacity c on path p",
    "    for each edge (u, v) in p:",
    "      flow(u, v) += c",
    "      flow(v, u) -= c",
    "    max_flow += c",
    "  return max_flow"
  ]
};
